version: "3.7"
services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "host"
    volumes:
      - ./suricata:/etc/suricata
      - ./logs:/var/log/suricata
    command: ["suricata", "-c", "/etc/suricata/suricata.yaml", "-i", "eth0"]

  monitor:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: suricata-monitor
    volumes:
      - ./logs:/var/log/suricata
      - ./suricata-monitor.py:/opt/suricata-monitor.py
    command: ["python", "/opt/suricata-monitor.py", "--interval", "1.0"]
